# Generated by Django 2.2.3 on 2019-07-23 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_address_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
                ('name_kana', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='zipcode',
            name='prefecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shopping.Prefecture'),
        ),
    ]
