# Generated by Django 2.2.3 on 2019-07-23 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20190723_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='prefecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopping.Prefecture'),
        ),
    ]
